// 21-frameworks/react/src/components/Form.js
import { useState } from "react";

function Form(props) {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");

  const handleSubmit = (event) => {
    event.preventDefault();
    props.submit({ title, content });
    event.target.reset();
  };

  return (
    <form onSubmit={handleSubmit}>
      <label htmlFor="title">Title:</label>
      <input
        id="title"
        type="text"
        onChange={(ev) => setTitle(ev.target.value)}
      />

      <label htmlFor="content">Content:</label>
      <textarea id="content" onChange={(ev) => setContent(ev.target.value)} />

      <button type="submit">Submit</button>
    </form>
  );
}

export default Form;

// 21-frameworks/vue/src/components/Form.vue
<template>
  <form @submit.prevent="handleSubmit">
    <label for="title">Title:</label>
    <input id="title" type="text" v-model="title" />

    <label for="content">Content:</label>
    <textarea id="content" v-model="content" />

    <button type="submit">Submit</button>
  </form>
</template>

<script>
export default {
  props: {
    submit: {
      type: Function,
      required: true,
    },
  },
  data() {
    return {
      title: "",
      content: "",
    };
  },
  methods: {
    handleSubmit(event) {
      this.submit({ title: this.title, content: this.content });
      event.target.reset();
    },
  },
};
</script>
