// 42-a11y-selectors/angular/example-app/app/components/create-profile.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'create-profile',
  template: `
    <div>
      <h1>Create new post</h1>
      <success-message *ngIf="userCreated; else form" [user]="user"></success-message>
      <ng-template #form>
        <create-post-form [submit]="createPost.bind(this)"></create-post-form>
      </ng-template>
    </div>
  `,
})
export class CreateProfileComponent {
  user:any = null;
  
  createPost(data) {
    this.user = data
  }

  get userCreated() {
    return !!this.user?.name;
  }
}

// 41-a11y-axe/react/src/components/CreateProfile.js
import { useState } from "react";
import { createUser } from "../services/userRepository";
import Form from "./Form";
import SuccessMessage from "./SuccessMessage";

function Profile() {
  const [user, setUser] = useState({});

  function submit(data) {
    createUser(data).then((newUser) => {
      setUser(newUser);
    });
  }

  const userCreated = !!user?.name;

  return (
    <div>
      <h1>Create profile</h1>
      {userCreated ? <SuccessMessage user={user} /> : <Form submit={submit} />}
    </div>
  );
}

export default Profile;
