// 21-frameworks/react/src/components/Form.js
import { useState } from "react";

function Form(props) {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");

  const handleSubmit = (event) => {
    event.preventDefault();
    props.submit({ title, content });
    event.target.reset();
  };

  return (
    <form onSubmit={handleSubmit}>
      <label htmlFor="title">Title:</label>
      <input
        id="title"
        type="text"
        onChange={(ev) => setTitle(ev.target.value)}
      />

      <label htmlFor="content">Content:</label>
      <textarea id="content" onChange={(ev) => setContent(ev.target.value)} />

      <button type="submit">Submit</button>
    </form>
  );
}

export default Form;

// 21-frameworks/angular/src/app/components/form.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'create-post-form',
  template: `
  <form (submit)="handleSubmit($event)">
    <label for="title">Title:</label>
    <input
      id="title"
      type="text"
      [value]="title"
      (input)="updateTitle($event.target.value)"
    >

    <label for="content">Content:</label>
    <textarea id="content" [value]="content" (input)="updateContent($event.target.value)"></textarea>

    <button type="submit">Submit</button>
  </form>`,
})
export class FormComponent {
  @Input() submit;
  title = '';
  content = '';

  updateTitle(value) {
    this.title = value
  }

  updateContent(value) {
    this.content = value
  }

  handleSubmit(event) {
    event.preventDefault();
    this.submit({ title: this.title, content: this.content });
    event.target.reset();
  }
}
